apiVersion: v1
kind: Pod
metadata:
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "1234"
  name: prometheus-net-7
spec:
  nodeSelector:
    purpose: general
    nodegroup-colour: red
  containers:
    - name: prometheus-net
      image: daverant/prometheus-net:7
      ports:
        - containerPort: 1234
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 256Mi

---

apiVersion: v1
kind: Pod
metadata:
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "1234"
  name: prometheus-net-8
spec:
  nodeSelector:
    purpose: general
    nodegroup-colour: red
  containers:
    - name: prometheus-net
      image: daverant/prometheus-net:8
      ports:
        - containerPort: 1234
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 256Mi
